version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reelix_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - reelix

  nginx:
    image: nginx:alpine
    container_name: reelix_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - reelix

  db:
    image: postgres:15
    container_name: reelix_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - reelix
    volumes:
      - pgdata:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    container_name: reelix_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - reelix


networks:
  reelix:

volumes:
  pgdata:
